// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qoqxxvpihxctegnlpztl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvcXh4dnBpaHhjdGVnbmxwenRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MjQyMjQsImV4cCI6MjA2NjAwMDIyNH0.nj503HOh4qgo4JlNq06lf8mPCF1sp9zr5o0iATwkrc4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);